### ISSUE TITLE
order serializer fails on certain versions of solidus

### ISSUE THREAD

**Issue by AdnanTheExcellent** [solidusio-contrib/solidus_tracking#15]
https://github.com/solidusio-contrib/solidus_tracking/blob/master/lib/solidus_tracking/serializer/order.rb#L17

in Solidus 2.9.x, the line linked above fails with the following error message:

 `NoMethodError: undefined method 'code' for #<Spree::OrderPromotion:0x...>`

the line:

`'DiscountCode' => order.order_promotions.map { |op| op.code.value }.join(', '),`

should be to:

`'DiscountCode' => order.order_promotions.map { |op| op.promotion_code.value }.join(', '),`

I'm not sure which versions of solidus use `code` vs `promotion_code`, but I'm guessing there should be something to handle pre and post refactor of the promotion codes.

**Comment by aldesantis** [comment]
@AdnanTheExcellent thanks! I don't think there are any versions of Solidus that use `code`, I think it's just a bug. 🙁 I'll push a fix next week.
