### ISSUE TITLE
Prepare Solidus Tracking for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_tracking#18]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by AlistairNorman** [comment]
I'll take this one!

**Comment by AlistairNorman** [comment]
This passes without deprecation all the way up to master already so looks like it's good to go without changes!

**Comment by seand7565** [comment]
Closing since it looks like there's nothing to do here!
